import { config, library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

// Import only the icons we actually use for better tree-shaking
// Solid icons
import {
    faAddressBook,
    faArrowLeft,
    faArrowRight,
    faBars,
    faBookOpen,
    faBriefcase,
    faBuilding,
    faCalendar,
    faCertificate,
    faChartLine,
    faCheck,
    faChevronDown,
    faCloudSun,
    faCode,
    faComments,
    faDownload,
    faEdit,
    faEnvelope,
    faExclamationCircle,
    faExternalLinkAlt,
    faFileDownload,
    faFire,
    faFolder,
    faGlobe,
    faGraduationCap,
    faHome,
    faLightbulb,
    faMapMarkerAlt,
    faMobileAlt,
    faPalette,
    faPaperPlane,
    faPlus,
    faRightToBracket,
    faRobot,
    faSave,
    faShareAlt,
    faSignOutAlt,
    faSpinner,
    faTerminal,
    faTimes,
    faTrash,
    faTrophy,
    faUser,
    faUserDoctor,
    faUtensils,
    faWallet,
    faBookMedical,
} from "@fortawesome/free-solid-svg-icons";

// Brand icons (9)
import {
    faAndroid,
    faFreeCodeCamp,
    faGitAlt,
    faGithub,
    faGoogle,
    faGooglePlay,
    faLinux,
    faLinkedin,
    faTwitter,
} from "@fortawesome/free-brands-svg-icons";

// This is important, we are going to let Nuxt worry about the CSS
config.autoAddCss = true;

// Add only the icons we need
library.add(
    // Solid icons
    faAddressBook,
    faArrowLeft,
    faArrowRight,
    faBars,
    faBookOpen,
    faBriefcase,
    faBuilding,
    faCalendar,
    faCertificate,
    faChartLine,
    faCheck,
    faChevronDown,
    faCloudSun,
    faCode,
    faComments,
    faDownload,
    faEdit,
    faEnvelope,
    faExclamationCircle,
    faExternalLinkAlt,
    faFileDownload,
    faFire,
    faFolder,
    faGlobe,
    faGraduationCap,
    faHome,
    faLightbulb,
    faMapMarkerAlt,
    faMobileAlt,
    faPalette,
    faPaperPlane,
    faPlus,
    faRightToBracket,
    faRobot,
    faSave,
    faShareAlt,
    faSignOutAlt,
    faSpinner,
    faTerminal,
    faTimes,
    faTrash,
    faTrophy,
    faUser,
    faUserDoctor,
    faUtensils,
    faWallet,
    faBookMedical,
    // Brand icons
    faAndroid,
    faFreeCodeCamp,
    faGitAlt,
    faGithub,
    faGoogle,
    faGooglePlay,
    faLinux,
    faLinkedin,
    faTwitter
);

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.component("FaIcon", FontAwesomeIcon);
});
